"""add composite index on events service environment timestamp

Revision ID: b1258cbe0ce6
Revises: 0df360ae88de
Create Date: 2026-09-09 12:54:30.643307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1258cbe0ce6'
down_revision: Union[str, Sequence[str], None] = '0df360ae88de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_events_service_environment_timestamp', 'events', ['service', 'environment', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_service_environment_timestamp', table_name='events')
    # ### end Alembic commands ###
